import { Component, ElementRef, OnInit } from '@angular/core';
import { DataGestanteInterface } from 'src/app/interface/data-gestante-interface';

@Component({
  selector: 'app-gestantes-listado',
  templateUrl: './gestantes-listado.component.html',
  styleUrls: ['./gestantes-listado.component.scss']
})
export class GestantesListadoComponent implements OnInit {
  selected_row: number = -1;

  filtro: any
  gestante_detalle: DataGestanteInterface = { "ID_PERSONA": 1, "NOMBRES": "ADELINA ", "APELLIDO_PAT": "LUCANO ", "APELLIDO_MAT": "EUGENIO", "ID_TIPOD": 1, "NRO_DOCUMENTO": "47198873", "FECHA_NAC": "1991-09-03T00:00:00", "ID_DISTRITO": "060701", "ID_PROVINCIA": "0607", "ID_DEPARTAMENTO": "06", "DIRECCION": "LLAUCAN", "TELEFONO": "PENDIENTE", "CORREO": "PENDIENTE", "ID_GENERO": 2, "NOMBRES_COMP": "ADELINA  LUCANO  EUGENIO" }
  constructor() { }

  fila_ant!: ElementRef

  data_gestante: DataGestanteInterface[] = [
    { "ID_PERSONA": 1, "NOMBRES": "ADELINA ", "APELLIDO_PAT": "LUCANO ", "APELLIDO_MAT": "EUGENIO", "ID_TIPOD": 1, "NRO_DOCUMENTO": "47198873", "FECHA_NAC": "1991-09-03T00:00:00", "ID_DISTRITO": "060701", "ID_PROVINCIA": "0607", "ID_DEPARTAMENTO": "06", "DIRECCION": "LLAUCAN", "TELEFONO": "PENDIENTE", "CORREO": "PENDIENTE", "ID_GENERO": 2, "NOMBRES_COMP": "ADELINA  LUCANO  EUGENIO" },
    { "ID_PERSONA": 2, "NOMBRES": "CONSUELO ", "APELLIDO_PAT": "OLIVARES", "APELLIDO_MAT": "CAMPOS", "ID_TIPOD": 1, "NRO_DOCUMENTO": "42359805", "FECHA_NAC": "1984-02-03T00:00:00", "ID_DISTRITO": "060701", "ID_PROVINCIA": "0607", "ID_DEPARTAMENTO": "06", "DIRECCION": "MARAYPAMPA", "TELEFONO": "PENDIENTE", "CORREO": "PENDIENTE", "ID_GENERO": 2, "NOMBRES_COMP": "CONSUELO  OLIVARES CAMPOS" }, { "ID_PERSONA": 3, "NOMBRES": "SOFIA NELY", "APELLIDO_PAT": "CRUZADO", "APELLIDO_MAT": "CAMPOS", "ID_TIPOD": 1, "NRO_DOCUMENTO": "41196356", "FECHA_NAC": "1981-12-25T00:00:00", "ID_DISTRITO": "060701", "ID_PROVINCIA": "0607", "ID_DEPARTAMENTO": "06", "DIRECCION": "LUCMACUCHO", "TELEFONO": "PENDIENTE", "CORREO": "PENDIENTE", "ID_GENERO": 2, "NOMBRES_COMP": "SOFIA NELY CRUZADO CAMPOS" }, { "ID_PERSONA": 4, "NOMBRES": "FLOR AIDE", "APELLIDO_PAT": "HERRERA ", "APELLIDO_MAT": "HUAMAN", "ID_TIPOD": 1, "NRO_DOCUMENTO": "74360222", "FECHA_NAC": "2002-05-22T00:00:00", "ID_DISTRITO": "060701", "ID_PROVINCIA": "0607", "ID_DEPARTAMENTO": "06", "DIRECCION": "HUALANGA ALTA", "TELEFONO": "PENDIENTE", "CORREO": "PENDIENTE", "ID_GENERO": 2, "NOMBRES_COMP": "FLOR AIDE HERRERA  HUAMAN" }, { "ID_PERSONA": 5, "NOMBRES": "MERLY  ", "APELLIDO_PAT": "JULON ", "APELLIDO_MAT": "GARCIA", "ID_TIPOD": 1, "NRO_DOCUMENTO": "72418231", "FECHA_NAC": "2002-12-12T00:00:00", "ID_DISTRITO": "060701", "ID_PROVINCIA": "0607", "ID_DEPARTAMENTO": "06", "DIRECCION": "PASAUMACA", "TELEFONO": "PENDIENTE", "CORREO": "PENDIENTE", "ID_GENERO": 2, "NOMBRES_COMP": "MERLY   JULON  GARCIA" }, { "ID_PERSONA": 6, "NOMBRES": "JUANA ", "APELLIDO_PAT": "NORIEGA ", "APELLIDO_MAT": "DURAN", "ID_TIPOD": 1, "NRO_DOCUMENTO": "41506242", "FECHA_NAC": "1976-11-03T00:00:00", "ID_DISTRITO": "060701", "ID_PROVINCIA": "0607", "ID_DEPARTAMENTO": "06", "DIRECCION": "HUALANAGA BAJA", "TELEFONO": "PENDIENTE", "CORREO": "PENDIENTE", "ID_GENERO": 2, "NOMBRES_COMP": "JUANA  NORIEGA  DURAN" }, { "ID_PERSONA": 7, "NOMBRES": "IRMA ", "APELLIDO_PAT": "ESCOBAR ", "APELLIDO_MAT": "ACUÑA ", "ID_TIPOD": 1, "NRO_DOCUMENTO": "80105119", "FECHA_NAC": "1974-12-20T00:00:00", "ID_DISTRITO": "060701", "ID_PROVINCIA": "0607", "ID_DEPARTAMENTO": "06", "DIRECCION": "HUALANGA ALTA", "TELEFONO": "PENDIENTE", "CORREO": "PENDIENTE", "ID_GENERO": 2, "NOMBRES_COMP": "IRMA  ESCOBAR  ACUÑA " }, { "ID_PERSONA": 8, "NOMBRES": "LUZ ROSELIA", "APELLIDO_PAT": "CHAVEZ", "APELLIDO_MAT": "TERRONES", "ID_TIPOD": 1, "NRO_DOCUMENTO": "72438916", "FECHA_NAC": "1999-06-03T00:00:00", "ID_DISTRITO": "060701", "ID_PROVINCIA": "0607", "ID_DEPARTAMENTO": "06", "DIRECCION": "TAMBILLO", "TELEFONO": "PENDIENTE", "CORREO": "PENDIENTE", "ID_GENERO": 2, "NOMBRES_COMP": "LUZ ROSELIA CHAVEZ TERRONES" }, { "ID_PERSONA": 9, "NOMBRES": "CENAYDA ", "APELLIDO_PAT": "GALLARDO", "APELLIDO_MAT": "ESPINOZA", "ID_TIPOD": 1, "NRO_DOCUMENTO": "47264909", "FECHA_NAC": "1992-08-30T00:00:00", "ID_DISTRITO": "060701", "ID_PROVINCIA": "0607", "ID_DEPARTAMENTO": "06", "DIRECCION": "QUINUA ALTA", "TELEFONO": "PENDIENTE", "CORREO": "PENDIENTE", "ID_GENERO": 2, "NOMBRES_COMP": "CENAYDA  GALLARDO ESPINOZA" }, { "ID_PERSONA": 10, "NOMBRES": "KEYLER ", "APELLIDO_PAT": "ESPINOZA ", "APELLIDO_MAT": "LUCANO", "ID_TIPOD": 1, "NRO_DOCUMENTO": "72456627", "FECHA_NAC": "1996-12-27T00:00:00", "ID_DISTRITO": "060701", "ID_PROVINCIA": "0607", "ID_DEPARTAMENTO": "06", "DIRECCION": "LA HUAYLLA", "TELEFONO": "PENDIENTE", "CORREO": "PENDIENTE", "ID_GENERO": 2, "NOMBRES_COMP": "KEYLER  ESPINOZA  LUCANO" }, { "ID_PERSONA": 11, "NOMBRES": "FLOR  ALICIA", "APELLIDO_PAT": "CRUZADO", "APELLIDO_MAT": "ORTIZ", "ID_TIPOD": 1, "NRO_DOCUMENTO": "72436290          ", "FECHA_NAC": "2005-05-13T00:00:00", "ID_DISTRITO": "060701", "ID_PROVINCIA": "0607", "ID_DEPARTAMENTO": "06", "DIRECCION": "SAN ANTONIO BAJO", "TELEFONO": "PENDIENTE", "CORREO": "PENDIENTE", "ID_GENERO": 2, "NOMBRES_COMP": "FLOR  ALICIA CRUZADO ORTIZ" }, { "ID_PERSONA": 12, "NOMBRES": "LUZ ELENA", "APELLIDO_PAT": "MEJIA ", "APELLIDO_MAT": "ROJAS", "ID_TIPOD": 1, "NRO_DOCUMENTO": "46637870          ", "FECHA_NAC": "1990-11-23T00:00:00", "ID_DISTRITO": "060701", "ID_PROVINCIA": "0607", "ID_DEPARTAMENTO": "06", "DIRECCION": "SAN ANTONIO BAJO", "TELEFONO": "PENDIENTE", "CORREO": "PENDIENTE", "ID_GENERO": 2, "NOMBRES_COMP": "LUZ ELENA MEJIA  ROJAS" }, { "ID_PERSONA": 13, "NOMBRES": "LUZ  ELINA", "APELLIDO_PAT": "BUSTAMANTE", "APELLIDO_MAT": "TIRADO", "ID_TIPOD": 1, "NRO_DOCUMENTO": "47089427          ", "FECHA_NAC": "1986-03-15T00:00:00", "ID_DISTRITO": "060701", "ID_PROVINCIA": "0607", "ID_DEPARTAMENTO": "06", "DIRECCION": "BAMBAMARCA", "TELEFONO": "PENDIENTE", "CORREO": "PENDIENTE", "ID_GENERO": 2, "NOMBRES_COMP": "LUZ  ELINA BUSTAMANTE TIRADO" }, { "ID_PERSONA": 14, "NOMBRES": "IRENE ", "APELLIDO_PAT": "BUSTAMANTE", "APELLIDO_MAT": "SILVA", "ID_TIPOD": 1, "NRO_DOCUMENTO": "47031921", "FECHA_NAC": "1990-07-01T00:00:00", "ID_DISTRITO": "060701", "ID_PROVINCIA": "0607", "ID_DEPARTAMENTO": "06", "DIRECCION": "BAMBAMARCA", "TELEFONO": "PENDIENTE", "CORREO": "PENDIENTE", "ID_GENERO": 2, "NOMBRES_COMP": "IRENE  BUSTAMANTE SILVA" }, { "ID_PERSONA": 15, "NOMBRES": "SINTIA ", "APELLIDO_PAT": "PENAS", "APELLIDO_MAT": "CARUAJULCA", "ID_TIPOD": 1, "NRO_DOCUMENTO": "73439843", "FECHA_NAC": "1999-12-08T00:00:00", "ID_DISTRITO": "060701", "ID_PROVINCIA": "0607", "ID_DEPARTAMENTO": "06", "DIRECCION": "BAMBAMARCA", "TELEFONO": "PENDIENTE", "CORREO": "PENDIENTE", "ID_GENERO": 2, "NOMBRES_COMP": "SINTIA  PENAS CARUAJULCA" }]
  data_encontrada = this.data_gestante
  ngOnInit(): void {

    console.log(this.data_gestante.length)
  }

  Buscar(e: any) {
    if (this.filtro == '') {
      this.data_encontrada = this.data_gestante

      return
    }
    this.data_encontrada = this.data_gestante.filter(data => { return data.NRO_DOCUMENTO == this.filtro })
  }
  visualizar_detalle(data: DataGestanteInterface, index: number) {
    this.gestante_detalle = data;
    this.selected_row = index;

  }

}
